### ISSUE TITLE
api 0.5.2 error

### ISSUE THREAD

**Issue by springeye** [benjaminRomano/atom-bottom-dock#1]
After using 0.5.2. Atom startup error. Tools develop is not realistic any errors

``` json
.......
......

  "engines": {
    "atom": ">=1.0.0"
  },
  "dependencies": {
    "ansi-to-html": "^0.3.0",
    "atom-bottom-dock": "^0.5.2",
    "space-pen": "^5.1.1"
  },
  "packageDependencies": {
    "bottom-dock": "^0.3.5"
  },
  "consumedServices": {
    "bottom-dock": {
      "versions": {
        "^0.2.0": "consumeBottomDock"
      }
    }
  }

......
......
```

**Comment by benjaminRomano** [comment]
I'm assuming this is for the gulp-manager package.

I tested it locally and setting atom-bottom-dock to v0.5.2 didn't cause any errors on my end.

**Comment by springeye** [comment]
另一个问题：
判断判断@bottomDock是否激活（显示）
Another question:
To determine whether @bottomDock is activated (display).

``` js
class BottomDockService {
  toggle(): void
  changePane(id: string): void
  deletePane(id: string): void
  getPane(id: string): Pane //Where Pane extends DockPaneView
  addPane(pane: Pane, tab: TabButton): void
  getCurrentPane(): Pane
  deleteCurrentPane: void
  onDidChangePane(callback: (id: string) => void): Disposable
  onDidDeletePane(callback: (id: string) => void): Disposable
  onDidFinishResizing(callback: () => void): Disposable
}
```

**Comment by benjaminRomano** [comment]
I added an onDidToggle event and isActive function to the API.
This should make it possible to check whether @bottomDock is activated.

Check out https://github.com/benjaminRomano/bottom-dock for more info.

**Comment by benjaminRomano** [comment]
I fixed the bug you were having in the latest version (v0.5.3).

The problem was that atom-bottom-dock wasn't adding jQuery onto the window object, which slick-grid (the table library) requires.

**Comment by springeye** [comment]
good
